env:
  browser: true
  es2021: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
rules:
    "@typescript-eslint/prefer-nullish-coalescing": "off"
    "@typescript-eslint/strict-boolean-expressions": "off"
    "@typescript-eslint/no-namespace": "off"
    "@typescript-eslint/method-signature-style": "off"
    "@typescript-eslint/no-unused-vars": "off"
    "@typescript-eslint/no-unused-expressions": "off"
    "@typescript-eslint/no-invalid-void-type": "off"

