/*
   Copyright 2026 WeAreFrank!

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.wearefrank.ladybug.test.webapp.test.webapp;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.wearefrank.ladybug.Checkpoint;
import org.wearefrank.ladybug.Report;
import org.wearefrank.ladybug.Rerunner;
import org.wearefrank.ladybug.SecurityContext;
import org.wearefrank.ladybug.TestTool;
import org.wearefrank.ladybug.run.ReportRunner;

import lombok.Setter;

public class SimpleRerunner implements Rerunner {
	@Setter @Autowired TestTool testTool;

	@Override
	public String rerun(String correlationId, Report originalReport,
			SecurityContext securityContext, ReportRunner reportRunner) {
		if(! rerunSpecialReport(correlationId, originalReport, securityContext, reportRunner)) {
			rerunDefault(correlationId, originalReport, securityContext, reportRunner);
		}
		return null;
	}

	/**
	 * Rerun a report that we want to investigate in the ladybug-frontend Cypress tests.
	 * For some reports, we want to edit them during the tests such that they will succeed
	 * on rerun.
	 * 
	 * @param correlationId
	 * @param originalReport
	 * @param securityContext
	 * @param reportRunner
	 * @return
	 */
	private boolean rerunSpecialReport(String correlationId, Report originalReport,
			SecurityContext securityContext, ReportRunner reportRunner) {
		if(new HashSet<>(Arrays.asList("Simple report", "Another simple report")).contains(originalReport.getName())) {
			testTool.startpoint(correlationId, null, originalReport.getName(), "Hello Original World!");
			testTool.endpoint(correlationId, null, originalReport.getName(), "Goodbye Original World!");
			return true;
		}
		return false;
	}

	private void rerunDefault(String correlationId, Report originalReport,
			SecurityContext securityContext, ReportRunner reportRunner) {
		List<Checkpoint> checkpoints = originalReport.getCheckpoints();
		String name = checkpoints.get(0).getName();
		String message = checkpoints.get(0).getMessage();
		testTool.startpoint(correlationId, this.getClass().getName(), name, message);
		testTool.infopoint(correlationId, this.getClass().getName(), "PLEASE NOTE",
				"This report is generated by SimpleRerunner which wil only copy the first and last checkpoint from the"
				+ " original report and discard all otehr checkpoint and it doesn't run any business logic like a"
				+ " normal Rerunner should do!");
		name = checkpoints.get(checkpoints.size() - 1).getName();
		message = checkpoints.get(checkpoints.size() - 1).getMessage();
		testTool.endpoint(correlationId, this.getClass().getName(), name, message);
	}
}
