jdbc.migrator.active=true
ladybug.jdbc.datasource=jdbc/frank-console-holder
# File must be present because otherwise logging is not initialized
warnings.suppress.sqlInjections=true
warnings.suppress.sqlInjections.ManageDatabase=true
warnings.suppress.unsafeAttribute=true
warnings.suppress.transaction=true
