spring.application.name=ladybug-spring-boot
server.port=80
spring.mvc.view.prefix=/index
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/
spring.mvc.servlet.path=/ladybug/api/
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
