# This setting modifies the UI to act as if an IbisTester was logged in
# The backend still respects the real user role.
# This allows Ladybug developers to test whether the
# backend blocks unauthorized use. The backend should
# do so because attackers can send HTTP requests
# to the backend directly.
#
# ladybug.ui.test.mode=dont_block_backend
#
# This setting makes the UI behave as desired for normal use.
# The UI guides the user not to try unauthorized actions.
ladybug.ui.test.mode=default