# When this file is missing on the classpath as is the case when
# ladybug is not part of ladybug-test-webapp, then Ladybug will
# behave as if ladybug.ui.test.mode=default and
# ladybug.backend.throws.fake.exceptions=false
#
# The below setting modifies the UI to act as if an IbisTester was logged in.
# The backend still respects the real user role.
# This allows Ladybug developers to test whether the
# backend blocks unauthorized use. The backend should
# do so because attackers can send HTTP requests
# to the backend directly.
#
# ladybug.ui.test.mode=DONT_BLOCK_BACKEND
ladybug.ui.test.mode=DEFAULT
#
# The below setting lets the ladybug backend throw fake exceptions,
# allowing ladybug testers to see how exceptions are handled.
# ladybug.backend.throws.fake.exceptions=true
ladybug.backend.throws.fake.exceptions=false
#
# When ladybug.backend.throws.fake.exceptions=true we do not want to
# throw exceptions too often. Put a number here to control the
# amount of exceptions.
ladybug.backend.fake.exception.call.count=5
